// Code generated by MockGen. DO NOT EDIT.
// Source: dialogflow.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	clients "github.com/opendroid/the-gpl/clients"
)

// MockDialogflowBot is a mock of DialogflowBot interface.
type MockDialogflowBot struct {
	ctrl     *gomock.Controller
	recorder *MockDialogflowBotMockRecorder
}

// MockDialogflowBotMockRecorder is the mock recorder for MockDialogflowBot.
type MockDialogflowBotMockRecorder struct {
	mock *MockDialogflowBot
}

// NewMockDialogflowBot creates a new mock instance.
func NewMockDialogflowBot(ctrl *gomock.Controller) *MockDialogflowBot {
	mock := &MockDialogflowBot{ctrl: ctrl}
	mock.recorder = &MockDialogflowBotMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDialogflowBot) EXPECT() *MockDialogflowBotMockRecorder {
	return m.recorder
}

// Converse mocks base method.
func (m *MockDialogflowBot) Converse(s *clients.DialogflowSession, q string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Converse", s, q)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Converse indicates an expected call of Converse.
func (mr *MockDialogflowBotMockRecorder) Converse(s, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Converse", reflect.TypeOf((*MockDialogflowBot)(nil).Converse), s, q)
}
