// Code generated by MockGen. DO NOT EDIT.
// Source: anthropic.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAnthropicClient is a mock of AnthropicClient interface.
type MockAnthropicClient struct {
	ctrl     *gomock.Controller
	recorder *MockAnthropicClientMockRecorder
}

// MockAnthropicClientMockRecorder is the mock recorder for MockAnthropicClient.
type MockAnthropicClientMockRecorder struct {
	mock *MockAnthropicClient
}

// NewMockAnthropicClient creates a new mock instance.
func NewMockAnthropicClient(ctrl *gomock.Controller) *MockAnthropicClient {
	mock := &MockAnthropicClient{ctrl: ctrl}
	mock.recorder = &MockAnthropicClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnthropicClient) EXPECT() *MockAnthropicClientMockRecorder {
	return m.recorder
}

// Ask mocks base method.
func (m *MockAnthropicClient) Ask(ctx context.Context, systemPrompt, userContent string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ask", ctx, systemPrompt, userContent)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ask indicates an expected call of Ask.
func (mr *MockAnthropicClientMockRecorder) Ask(ctx, systemPrompt, userContent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ask", reflect.TypeOf((*MockAnthropicClient)(nil).Ask), ctx, systemPrompt, userContent)
}
